CREATE TABLE SAMPLE(
	ID INT,
	NAME VARCHAR(20)
);

-- desc SAMPLE;
INSERT INTO SAMPLE(ID,NAME)
VALUES(10,'VIJAY'),(20,'SWATHI'),(30,'DHEEKSHA');

SELECT * FROM SAMPLE;

INSERT INTO SAMPLE VALUES(40,'SHENBA');

SELECT * FROM SAMPLE WHERE NAME LIKE 'V%';

CREATE VIEW START_V_NAME_VIEW AS ( SELECT * FROM SAMPLE WHERE NAME LIKE 'V%' );

SELECT * FROM START_V_NAME_VIEW;

INSERT INTO SAMPLE VALUES(50,'VETRI');

DELETE FROM SAMPLE WHERE NAME = 'VETRI';

CREATE OR REPLACE FUNCTION ADD_NUMBERS(A INT, B INT) RETURNS INT LANGUAGE SQL
AS $$
	SELECT A+B
   $$;

SELECT ADD_NUMBERS(5,5);

CREATE DATABASE AMADIS_TRAINING;
