CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    bonus DECIMAL(10,2),
    age INT
);

INSERT INTO employees
VALUES
(101,'Vijay','IT',50000,5000,23),
(102,'Arun','HR',45000,NULL,25),
(103,'Priya','IT',70000,7000,24),
(104,'John','Finance',60000,NULL,29),
(105,'Meena','HR',55000,4000,22),
(106,'Kiran','IT',65000,NULL,27),
(107,'Divya','Finance',80000,8000,30),
(108,'Rahul','HR',40000,NULL,21);

SELECT * FROM employees;

-- COUNT

SELECT COUNT(*) FROM EMPLOYEES; -- 8 WITH NULL COUNTING
SELECT COUNT(BONUS) FROM EMPLOYEES;  --4 WITHOUT NULL COUNTING
SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'; -- IT DEPARTMENT COUNT
SELECT COUNT(DEPARTMENT) FROM EMPLOYEES; -- COUNT IF DEPARTMENT IS NOT NULL SO 8.
SELECT COUNT(DISTINCT DEPARTMENT) FROM EMPLOYEES; -- COUNT ONLY UNIQUE SO 3.
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEES
	GROUP BY DEPARTMENT; -- GROUP BY DEPARTMENT AND COUNT EACH DEPARTMENT CONTAINS HOW MANY TIMES.
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING COUNT(*) >= 3; -- SAME ABOVE BUT ONLY DISPLAYED ABOVE 3 COUNT USING HAVING
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING COUNT(*) >= 3
	ORDER BY DEPARTMENT ASC; -- SAME ABOVE BUT SORTING BY DEPARTMENT ASCENDING
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING COUNT(*) >= 3
	ORDER BY DEPARTMENT ASC
	LIMIT 1; -- FETCH ABOVE RESULT AND ONLY ONE ROW RETURNS USING LIMIT

-- SUM

SELECT SUM(SALARY) FROM EMPLOYEES; -- TOTAL SALARY OF ALL EMPLOYEES
SELECT SUM(BONUS) FROM EMPLOYEES; -- IGNORED NULL VALUES
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'; -- TOTAL SALARY OF DEPARTMENT WHOSE IT
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT; -- DEPARTMENT WISE TOTAL SALARY
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING SUM(SALARY) = 140000; -- DEPARTMENT WISE TOTAL SALARY AND GT THEN 140000
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING SUM(SALARY) = 140000
	ORDER BY DEPARTMENT DESC; -- DESCENDING ORDER PRINTING
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING SUM(SALARY) = 140000
	ORDER BY DEPARTMENT DESC
	LIMIT 1; -- ONLY ONE RECORD OF ABOVE QUERY

-- AVERAGE

SELECT AVG(SALARY) FROM EMPLOYEES; -- AVERAGE SALARY OF ALL EMPLOYEES
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR'; -- AVERAGE OF ALL EMPLOYEE ONLY DEPARTMENT IN HR
SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT; -- DEPARTMENT WISE AVG SALARY
SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING AVG(SALARY) > 50000; -- ABOVE 50000
SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING AVG(SALARY) > 50000
	ORDER BY DEPARTMENT DESC; -- DESCENDING ORDER
SELECT DEPARTMENT,AVG(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING AVG(SALARY) > 50000
	ORDER BY DEPARTMENT DESC
	LIMIT 1; -- ONLY ONE ROW
SELECT AVG(BONUS) FROM EMPLOYEES; -- ONLY NON NULL BONUS VALUES CONSIDERED.

-- MINIMUM

SELECT MIN(SALARY) FROM EMPLOYEES; -- MINIMUM SALARY EMPLOYEE DETAILS
SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'; -- IT DEPARTMENT MIN SALARY EMPLOYEE
SELECT DEPARTMENT,MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT; -- DEPARTMENT WISE MINIMUM SALARY
SELECT DEPARTMENT,MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MIN(SALARY) >= 50000; -- HAVING MORE THAN 50000
SELECT DEPARTMENT,MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MIN(SALARY) >= 50000
	ORDER BY DEPARTMENT DESC; -- DESCENDING ORDER
SELECT DEPARTMENT,MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MIN(SALARY) >= 50000
	ORDER BY DEPARTMENT DESC
	LIMIT 1; -- FIRST ROW RETURN

-- MAXIMUM

SELECT MAX(SALARY) FROM EMPLOYEES; -- MAX SALARY EMPLOYEE DETAILS
SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'; -- IT DEPARTMENT MAX SALARY EMPLOYEE
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT; -- DEPARTMENT WISE MAX SALARY
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MAX(SALARY) >= 60000; -- HAVING MORE THAN 50000
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MAX(SALARY) >= 60000
	ORDER BY DEPARTMENT DESC; -- DESCENDING ORDER
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING MAX(SALARY) >= 60000
	ORDER BY DEPARTMENT DESC
	LIMIT 1; -- FIRST ROW RETURN

-- AGGREGATE FUNCTION WITH MULTIPLE COLUMNS

SELECT 
	COUNT(*) AS TOTAL_EMPLOYEES,
	SUM(SALARY) AS TOTAL_SALARY,
	AVG(SALARY) AS AVERAGE_SALARY,
	MIN(SALARY) AS MINIMUM_SALARY,
	MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES;

-- PRACTICE QUERIES

-- 1. FIND TOTAL EMPLOYEES - 8
SELECT COUNT(*) FROM EMPLOYEES;

-- 2. FIND TOTAL SALARY OF HR DEPARTMENT
SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR';

-- 3. FIND AVERAGE SALARY FO IT DEPARTMENT
SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT';

-- 4. FIND HIGHEST SALARY IN FINANCE
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = 'Finance'
	ORDER BY SALARY DESC
	LIMIT 1;

-- 5. FIND MINIMUM SALARY DEPARTMENT WISE
SELECT DEPARTMENT,MIN(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT;

-- 6. FIND DEPARTMENTS HAVING MORE THAN 2 EMPLOYEES
SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING COUNT(*) > 2;

-- 7. FIND DEPARTMENTS WHOSE TOTAL SALARY IS GT THAN 150000.
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	HAVING SUM(SALARY) > 150000;

-- 8. FIND TOTAL BONUS EXCLUDING NULL VALUES
SELECT SUM(BONUS) FROM EMPLOYEES;

-- 9. FIND NUMBER OF EMPLOYEES WHO RECEIVED A BONUS
SELECT COUNT(BONUS) FROM EMPLOYEES;

-- 10. DISPLAY DEPARTMENT WISE EMPLOYEE COUNT IN DESCENDING ORDER
SELECT DEPARTMENT, COUNT(*) FROM EMPLOYEES
	GROUP BY DEPARTMENT
	ORDER BY COUNT(*) DESC;

-- BOTH WHERE AND HAVING

SELECT DEPARTMENT,COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEES
	WHERE SALARY > 50000
	GROUP BY DEPARTMENT
	HAVING COUNT(*) >= 2;

SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES
	WHERE AGE > 23
	GROUP BY DEPARTMENT
	HAVING SUM(SALARY) > 100000;

-- HAVING WITHOUT GROUP BY

SELECT COUNT(*) FROM EMPLOYEES
	HAVING COUNT(*) > 5;

-- DATE TRUNC

CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    bonus DECIMAL(10,2),
    age INT,
    joining_date DATE
);

INSERT INTO employees
VALUES
(101,'Vijay','IT',50000,5000,23,'2024-01-15'),
(102,'Arun','HR',45000,NULL,25,'2024-01-20'),
(103,'Priya','IT',70000,7000,24,'2024-02-12'),
(104,'John','Finance',60000,NULL,29,'2024-02-25'),
(105,'Meena','HR',55000,4000,22,'2024-03-18'),
(106,'Kiran','IT',65000,NULL,27,'2024-03-22'),
(107,'Divya','Finance',80000,8000,30,'2024-04-10'),
(108,'Rahul','HR',40000,NULL,21,'2024-04-15');

SELECT * FROM employees;

-- 1. GROUP BY EXPRESSION
SELECT 
	CASE
		WHEN SALARY >= 60000 THEN 'HIGH SALARY'
		ELSE 'LOW SALARY'
	END AS SALARY_CATEGORY,
	COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
GROUP BY 
	CASE
		WHEN SALARY >= 60000 THEN 'HIGH SALARY'
		ELSE 'LOW SALARY'
	END;

SELECT
	CASE
		WHEN AGE < 25 THEN 'FRESHER'
		ELSE 'EXPERIENCED'
	END AS CATEGORY,
	COUNT(*)
FROM EMPLOYEES
GROUP BY
	CASE
		WHEN AGE < 25 THEN 'FRESHER'
		ELSE 'EXPERIENCED'
	END;

-- 2. GROUP BY COLUMN POSITION

SELECT DEPARTMENT,COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES
	GROUP BY DEPARTMENT;

SELECT DEPARTMENT,COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES
	GROUP BY 1;

SELECT DEPARTMENT,AGE,COUNT(*) FROM EMPLOYEES
	GROUP BY 1,2;

-- 3. GROUP BY DATE_TRUNC()

SELECT DATE_TRUNC('month', JOINING_DATE) AS JOINING_MONTH, COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES
	GROUP BY DATE_TRUNC('month', JOINING_DATE)
	ORDER BY JOINING_MONTH;

SELECT DATE_TRUNC('year', JOINING_DATE) AS JOINING_YEAR, COUNT(*) FROM EMPLOYEES
	GROUP BY DATE_TRUNC('year', JOINING_DATE);

-- 4. GROUP BY WITH NUMERIC FUNCTION

SELECT ROUND(SALARY) AS ROUNDED_SALARY, COUNT(*) FROM EMPLOYEES
	GROUP BY ROUND(SALARY)
	ORDER BY ROUNDED_SALARY;

SELECT (AGE/10)*10 AS AGE_GROUP, COUNT(*) FROM EMPLOYEES
	GROUP BY (AGE/10)*10
	ORDER BY AGE_GROUP;

-- 5. GROUP BY WITHOUT AGGREGATION

SELECT DEPARTMENT FROM EMPLOYEES GROUP BY DEPARTMENT;

-- 6. CONDITIONAL AGGREGATION

SELECT COUNT(*) FILTER(WHERE DEPARTMENT = 'IT') AS IT_EMPLOYEES FROM EMPLOYEES;
SELECT
	COUNT(*) FILTER(WHERE DEPARTMENT = 'Finance') AS FINANCE_EMPLOYEES,
	COUNT(*) FILTER(WHERE DEPARTMENT = 'HR') AS HR_EMPLOYEES
FROM EMPLOYEES;
SELECT SUM(SALARY) FILTER(WHERE DEPARTMENT = 'IT') AS TOTAL_SALARY_OF_IT FROM EMPLOYEES;
SELECT MIN(SALARY) FILTER(WHERE DEPARTMENT = 'Finance') as LOWEST_OF_FINANCE FROM EMPLOYEES;
SELECT MAX(SALARY) FILTER(WHERE DEPARTMENT = 'HR') AS HIGHEST_OF_HR FROM EMPLOYEES;

-- 7. STRING AGGREGATION

SELECT STRING_AGG(EMPLOYEE_NAME,', ') FROM EMPLOYEES;
SELECT DEPARTMENT, STRING_AGG(EMPLOYEE_NAME,', ') FROM EMPLOYEES GROUP BY DEPARTMENT;
SELECT STRING_AGG(DISTINCT DEPARTMENT, ', ') FROM EMPLOYEES;

-- 8. CASE WHEN THEN

SELECT EMPLOYEE_NAME,SALARY,
	CASE
		WHEN SALARY >= 70000 THEN 'HIGH SALARY'
		WHEN SALARY >= 50000 THEN 'MEDIUM'
		ELSE 'LOW'
	END AS SALARY_CATEGORY
FROM EMPLOYEES;

SELECT EMPLOYEE_NAME,JOINING_DATE,
	CASE
		WHEN AGE < 23 THEN 'JUNIOR'
		WHEN AGE BETWEEN 23 AND 27 THEN 'MID LEVEL'
		ELSE 'SENIOR'
	END AS CATEGORY
FROM EMPLOYEES;

SELECT SUM(CASE WHEN DEPARTMENT = 'IT' THEN SALARY ELSE 0 END) FROM EMPLOYEES;

SELECT EMPLOYEE_NAME,SALARY,DEPARTMENT FROM EMPLOYEES
	ORDER BY
		CASE
			WHEN DEPARTMENT = 'IT' THEN 1
			WHEN DEPARTMENT = 'HR' THEN 2
			ELSE 3
		END;

SELECT EMPLOYEE_NAME,
	CASE
		WHEN AGE > 25 THEN 'ELIGIBLE'
	END
FROM EMPLOYEES;

-- 9. STATISTICAL AGGREGATES

SELECT VAR_POP(SALARY) AS VARIANCE FROM EMPLOYEES;
SELECT VAR_SAMP(SALARY) AS SAMP_VARIANCE FROM EMPLOYEES;
SELECT STDDEV_POP(SALARY) AS STD_SALARY FROM EMPLOYEES;
SELECT STDDEV_SAMP(SALARY) AS STD_SAMP FROM EMPLOYEES;
SELECT CORR(AGE,SALARY) FROM EMPLOYEES;
SELECT COVAR_POP(AGE,SALARY) FROM EMPLOYEES;
SELECT REGR_SLOPE(SALARY,AGE) FROM EMPLOYEES;

-- 10. WITHIN GROUP

SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY SALARY) FROM EMPLOYEES;
SELECT PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SALARY) FROM EMPLOYEES;
SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY SALARY) FROM EMPLOYEES;
SELECT MODE() WITHIN GROUP (ORDER BY DEPARTMENT) FROM EMPLOYEES;
SELECT PERCENTILE_CONT(ARRAY[0.25,0.5,0.75,1]) WITHIN GROUP (ORDER BY SALARY) FROM EMPLOYEES;