-- TABLE CREATION --

CREATE TABLE SIMPLE_TABLE(
	ID INT,
	NAME VARCHAR(20),
	DESCRIPTION TEXT,
	DOB DATE,
	PHONE VARCHAR(20),
	AMOUNT DECIMAL(10,2),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TEMPORARY TABLE TEMP_TABLE(
	ID INT,
	NAME VARCHAR(20),
	AMOUNT DECIMAL(10,2)
);

CREATE TABLE CTAS_SIMPLE_TABLE AS SELECT * FROM SIMPLE_TABLE;

WITH CTE_TABLE AS (SELECT * FROM SIMPLE_TABLE)
SELECT ID,NAME FROM CTE_TABLE;

-- ALTER TABLE --

	ALTER TABLE SIMPLE_TABLE ADD COLUMN SPL_ID INT;
	ALTER TABLE SIMPLE_TABLE ADD COLUMN EMAIL VARCHAR(20);
	ALTER TABLE SIMPLE_TABLE ADD COLUMN STATUS BOOLEAN DEFAULT FALSE;
	ALTER TABLE SIMPLE_TABLE ADD CONSTRAINT uq_email UNIQUE (EMAIL);
	ALTER TABLE SIMPLE_TABLE RENAME COLUMN PHONE TO PHONE_NUMBER;
	ALTER TABLE SIMPLE_TABLE ALTER COLUMN DESCRIPTION SET NOT NULL;
	ALTER TABLE SIMPLE_TABLE ALTER COLUMN DESCRIPTION DROP NOT NULL;
	ALTER TABLE SIMPLE_TABLE DROP COLUMN DESCRIPTION;
	ALTER TABLE SIMPLE_TABLE DROP COLUMN SPL_ID;
	ALTER TABLE SIMPLE_TABLE DROP COLUMN EMAIL;
	ALTER TABLE SIMPLE_TABLE DROP COLUMN STATUS;

	ALTER TABLE SIMPLE_TABLE RENAME TO SAMPLE_TABLE;
	ALTER TABLE SAMPLE_TABLE RENAME TO SIMPLE_TABLE;

-- DML COMMANDS --

SELECT * FROM SIMPLE_TABLE;

INSERT INTO SIMPLE_TABLE (ID,NAME,DOB,PHONE_NUMBER,AMOUNT)
VALUES
(1,'VIJAY','2000-11-13 11:00:09','+91 9000457089','5000.00'),
(2,'SWATHI','2000-04-07 11:00:09','+91 7263242348','8000.00');

INSERT INTO SIMPLE_TABLE (ID,NAME,DOB,PHONE_NUMBER,AMOUNT)
VALUES
(3,'DK','2000-11-13 11:00:09','+91 9000457089','5000.00');

UPDATE SIMPLE_TABLE
SET
	PHONE_NUMBER = '+91 6380712345',
	AMOUNT = '12000.00'
WHERE
	ID = 2 AND AMOUNT = '8000.00';

DELETE FROM SIMPLE_TABLE WHERE ID = 3;

TRUNCATE TABLE SIMPLE_TABLE;

DROP TABLE SIMPLE_TABLE;

-- VIEWS DEMONSTRATE -- 

INSERT INTO simple_table (id, name, description, dob, phone, amount)
VALUES
(1, 'Vijay', 'Developer', '2000-05-15', '9876543210', 50000),
(2, 'Arun', 'Tester', '1999-08-20', '9876543211', 40000),
(3, 'Priya', 'HR', '2001-02-10', '9876543212', 35000),
(4, 'Kiran', 'Manager', '1998-12-25', '9876543213', 80000),
(5, 'Meena', 'Developer', '2002-03-18', '9876543214', 60000);

SELECT * FROM simple_table;

CREATE VIEW EMPLOYEE_VIEW AS
SELECT ID,NAME,AMOUNT
FROM SIMPLE_TABLE;

SELECT * FROM employee_view;

CREATE VIEW high_salary AS
SELECT id, name, amount
FROM simple_table
WHERE amount > 50000;

SELECT * FROM high_salary;

UPDATE simple_table
SET amount = 90000
WHERE id = 1;

SELECT * FROM high_salary;
SELECT * FROM employee_view;

ALTER VIEW employee_view RENAME TO employee_details_view;
DROP VIEW employee_details_view;

SELECT table_name FROM information_schema.views
WHERE table_schema = 'public';

-- FUNCTIONS --

CREATE TABLE employee (
    id INT,
    name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2),
    age INT,
    joining_date DATE
);

INSERT INTO employee
VALUES
(1,'Vijay','IT',50000,23,'2024-01-15'),
(2,'Arun','HR',45000,25,'2023-05-10'),
(3,'Priya','IT',70000,27,'2022-03-12'),
(4,'John','Finance',60000,29,'2021-08-22'),
(5,'Meena','HR',55000,24,'2024-06-05');

SELECT * FROM employee;

-- AGGREGATE FUNCTIONS
SELECT COUNT(*) FROM EMPLOYEE;
SELECT SUM(SALARY) FROM EMPLOYEE;
SELECT MIN(SALARY) FROM EMPLOYEE;
SELECT MAX(SALARY) FROM EMPLOYEE;
SELECT AVG(SALARY) FROM EMPLOYEE;

-- STRING FUNCTIONS
SELECT NAME,UPPER(NAME) AS UPPER_CASE_NAME FROM EMPLOYEE;
SELECT NAME,LOWER(NAME) AS LOWER_CASE_NAME FROM EMPLOYEE;
SELECT NAME,LENGTH(NAME) AS LENGTHOFNAME FROM EMPLOYEE;
SELECT TRIM('    VIJAY   ') AS TRIMMING;
SELECT CONCAT(NAME,'-',DEPARTMENT) FROM EMPLOYEE;
SELECT LTRIM('    VIJAY   ') AS LTRIMMING;
SELECT RTRIM('    VIJAY   ') AS RTRIMMING;
SELECT NAME,SUBSTR(NAME,1,2) AS SUBSTRINGS FROM EMPLOYEE;
SELECT NAME,REPLACE(NAME,'VIJAY','VJ') FROM EMPLOYEE;
SELECT POSITION('V' IN NAME) FROM EMPLOYEE;
SELECT NAME,REVERSE(NAME) AS REV FROM EMPLOYEE;

-- NUMBER FUNCTIONS
SELECT ABS(-400);
SELECT CEIL(45.33);
SELECT FLOOR(23.43);
SELECT ROUND(343.53234,2);
SELECT POWER(12,4);
SELECT SQRT(65);
SELECT MOD(23,4);
SELECT RANDOM();

-- DATE FUNCTIONS
SELECT CURRENT_DATE;
SELECT CURRENT_TIME;
SELECT CURRENT_TIMESTAMP;
SELECT NOW();
SELECT AGE(JOINING_DATE) FROM EMPLOYEE;
SELECT EXTRACT(YEAR FROM JOINING_DATE) FROM EMPLOYEE;

-- CONVERSION FUNCTIONS
SELECT CAST(AGE AS VARCHAR);
SELECT SALARY::INTEGER FROM EMPLOYEE;

-- NULL FUNCTIONS
SELECT COALESCE(NULL,'No Data');
SELECT NULLIF(100,100);

-- AGGREGATE WITH GROUP BY AND HAVING AND DESC ASC AND LIMIT OFFSET
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT,SUM(SALARY) AS TOTAL FROM EMPLOYEE GROUP BY DEPARTMENT;
SELECT DEPARTMENT,SUM(SALARY) AS TOTAL FROM EMPLOYEE GROUP BY DEPARTMENT HAVING SUM(SALARY) >= 100000;
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY CNT DESC;
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY CNT DESC LIMIT 1;
SELECT DEPARTMENT,COUNT(*) AS CNT FROM EMPLOYEE GROUP BY DEPARTMENT ORDER BY CNT DESC LIMIT 1 OFFSET 1;

SELECT * FROM EMPLOYEE;

-- PROCEDURE --

CREATE OR REPLACE PROCEDURE get_all_employees()
LANGUAGE PLPGSQL
AS
$$
BEGIN
    RAISE NOTICE 'EMPLOYEE DETAILS';
END;
$$;

CALL get_all_employees();

CREATE OR REPLACE PROCEDURE total_employees()
LANGUAGE PLPGSQL
AS
$$
DECLARE
	TOTAL INT;
BEGIN
	SELECT COUNT(*) INTO TOTAL FROM EMPLOYEE;
	RAISE NOTICE 'TOTAL EMPLOYEES : %',TOTAL;
END;
$$;

CALL total_employees();

CREATE OR REPLACE PROCEDURE particular_employee_salary(empid INT)
LANGUAGE PLPGSQL
AS
$$
DECLARE
	EMP_SALARY DECIMAL;
BEGIN
	SELECT SALARY INTO EMP_SALARY FROM EMPLOYEE WHERE ID = empid;
	RAISE NOTICE 'SALARY OF % IS %',empid,emp_salary;
END;
$$;

CALL particular_employee_salary(2);

CREATE OR REPLACE PROCEDURE add_employee(
	e_id INT,
	e_name VARCHAR,
	e_department VARCHAR,
	e_salary DECIMAL,
	e_age INT,
	e_join_date DATE
)
LANGUAGE PLPGSQL AS
$$
	BEGIN
		INSERT INTO EMPLOYEE VALUES(e_id, e_name, e_department, e_salary, e_age, e_join_date);
		RAISE NOTICE 'INSERT DATA SUCCESSFULLY';
	END;
$$;
	
CALL add_employee(6,'Meena','HR',55000,24,'2024-06-05');

SELECT * FROM EMPLOYEE;
DELETE FROM EMPLOYEE WHERE ID = 6;

-- FUNCTION --

CREATE OR REPLACE FUNCTION total_salary() RETURNS INT
LANGUAGE SQL AS
$$
	SELECT SUM(salary) FROM EMPLOYEE;
$$;

SELECT total_salary();

CREATE OR REPLACE FUNCTION emp_salary(emp_id INT) RETURNS DECIMAL
LANGUAGE SQL AS
$$
	SELECT SALARY FROM EMPLOYEE WHERE id = emp_id;
$$;

SELECT emp_salary(1);

CREATE OR REPLACE FUNCTION get_employee_name(e_id INT) RETURNS VARCHAR
LANGUAGE SQL AS
$$
	SELECT NAME FROM EMPLOYEE WHERE id = e_id;
$$;

SELECT get_employee_name(3);

CREATE OR REPLACE FUNCTION employee_details(emp_id INT)
RETURNS TABLE(
	ID INT,
	NAME VARCHAR,
	DEPARTMENT VARCHAR,
	SALARY DECIMAL
)
LANGUAGE SQL
AS
$$
	SELECT ID,NAME,DEPARTMENT,SALARY FROM EMPLOYEE WHERE ID = emp_id;
$$;

SELECT employee_details(3);

-- JOINS -- 

CREATE TABLE departments (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(50)
);

INSERT INTO departments
VALUES
(101,'IT'),
(102,'HR'),
(103,'Finance'),
(104,'Sales');

CREATE TABLE employees (
    employee_id INT PRIMARY KEY,
    employee_name VARCHAR(50),
    salary DECIMAL(10,2),
    department_id INT
);

INSERT INTO employees
VALUES
(1,'Vijay',50000,101),
(2,'Arun',45000,102),
(3,'Priya',70000,101),
(4,'John',60000,103),
(5,'Meena',55000,NULL),
(6,'Kiran',65000,105);

SELECT * FROM departments;
SELECT * FROM employees;

SELECT * FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id;

SELECT e.employee_name, d.department_name, e.salary FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id;

SELECT * FROM employees e
LEFT JOIN departments d
ON e.department_id = d.department_id;

SELECT * FROM employees e
RIGHT JOIN departments d
ON e.department_id = d.department_id;

SELECT * FROM employees e
FULL OUTER JOIN departments d
ON e.department_id = d.department_id;

SELECT * FROM employees
CROSS JOIN departments;

CREATE TABLE employee_manager (
    employee_id INT,
    employee_name VARCHAR(50),
    manager_id INT
);

INSERT INTO employee_manager
VALUES
(1,'Vijay',3),
(2,'Arun',3),
(3,'Priya',NULL),
(4,'John',3),
(5,'Meena',4);

SELECT e.employee_name AS employee, m.employee_name AS manager FROM employee_manager e
LEFT JOIN employee_manager m
ON e.manager_id = m.employee_id;

SELECT e.employee_name, d.department_name FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id
WHERE d.department_name = 'IT';

SELECT e.employee_name, d.department_name, e.salary FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id
ORDER BY e.salary DESC;

SELECT d.department_name, COUNT(e.employee_id) AS total_employees FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id
GROUP BY d.department_name;

EXPLAIN (FORMAT JSON, ANALYZE, BUFFERS) SELECT * FROM EMPLOYEE;