-- WINDOW FUNCTIONS

-- 1. AGGREGATE

CREATE TABLE SALES(
	TRANSACTION_ID INT,
    STORE VARCHAR(20),
    SALES_AMOUNT DECIMAL(10,2)
);

INSERT INTO SALES
VALUES(1,'A',100.00),(2,'A',200.00),(3,'A',150.00),(4,'B',250.00),(5,'B',300.00);

SELECT * FROM SALES;

SELECT STORE,SUM(SALES_AMOUNT) AS AMOUNT FROM SALES
GROUP BY STORE; -- RESULTANT ROWS SHRINK

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER()
FROM SALES; -- CALCULATE SUM AND INSERT EVERY ROW

SELECT 
	TRANSACTION_ID,STORE,SALES_AMOUNT,
    SUM(SALES_AMOUNT) OVER(PARTITION BY STORE) AS TOTAL
FROM SALES; -- STORE WISE SUM ADDED FOR EVERY ROW

SELECT
	TRANSACTION_ID,STORE,SALES_AMOUNT,
	SUM(SALES_AMOUNT) OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT) AS TOTAL
FROM SALES; -- STORE WISE SUM ADDED IN INCREMENTAL WAY

-- 2. RANKING WINDOW FUNCTIONS

-- (i). ROW_NUMBER()

SELECT
	TRANSACTION_ID,STORE,SALES_AMOUNT,
	ROW_NUMBER() OVER()
FROM SALES;

SELECT
	TRANSACTION_ID,STORE,SALES_AMOUNT,
	ROW_NUMBER() OVER(ORDER BY SALES_AMOUNT DESC)
FROM SALES;

SELECT
	TRANSACTION_ID,STORE,SALES_AMOUNT,
	ROW_NUMBER() OVER(PARTITION BY STORE)
FROM SALES;

SELECT
	TRANSACTION_ID,STORE,SALES_AMOUNT,
	ROW_NUMBER() OVER(PARTITION BY STORE ORDER BY SALES_AMOUNT ASC)
FROM SALES;

-- (ii). RANK(), DENSE_RANK()

CREATE TABLE STUDENT_WINDOW(
	 STUDENT_ID INT,
     STUDENT_NAME VARCHAR(20),
     SCORE INT
);

INSERT INTO STUDENT_WINDOW
VALUES
(1, 'ALICE', 95),
(2, 'BOB', 90),
(3, 'CHARLIE', 95),
(4, 'DAVID', 85),
(5, 'EVA', 90);

SELECT *,
	RANK() OVER(ORDER BY SCORE DESC)
FROM STUDENT_WINDOW;

SELECT *,
	DENSE_RANK() OVER(ORDER BY SCORE DESC)
FROM STUDENT_WINDOW;

-- (iii). PERCENT_RANK() - FORMULA -> RANK OF THE ROW - 1 / TOTAL NUMBER OF ROWS - 1

SELECT *,
	PERCENT_RANK() OVER(ORDER BY SCORE DESC)
FROM STUDENT_WINDOW;

-- (iv). NTILE()

CREATE TABLE EMPLOYEE_NTILE_WINDOW(
	EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(20),
    SALES_AMOUNT DECIMAL(10,2)
);

INSERT INTO EMPLOYEE_NTILE_WINDOW
VALUES
(1, 'Alice', 10000),
(2, 'Bob', 8500),
(3, 'Charlie', 7500),
(4, 'David', 6000),
(5, 'Eva', 11000),
(6, 'Frank', 4500),
(7, 'Grace', 3000),
(8, 'Hank', 4000),
(9, 'Ivy', 8000),
(10, 'Jack', 9500);

SELECT * FROM EMPLOYEE_NTILE_WINDOW;

SELECT *,
	NTILE(4) OVER(ORDER BY SALES_AMOUNT DESC)
FROM EMPLOYEE_NTILE_WINDOW;

-- 3. VALUE WINDOW FUNCTION

-- (i). LAG()


CREATE TABLE EMPLOYEE_VALUE_WINDOW(
	EMPLOYEE_ID INT,
    EMPLOYEE_NAME VARCHAR(20),
    SALARY DECIMAL(10,2),
    YEAR VARCHAR(10)
);

INSERT INTO EMPLOYEE_VALUE_WINDOW
VALUES
(1, 'Alice', 5000.00, 2023),
(1, 'Alice', 5500.00, 2024),
(2, 'Bob', 4500.00, 2023),
(2, 'Bob', 4800.00, 2024),
(3, 'Charlie', 4000.00, 2023),
(3, 'Charlie', 4200.00, 2024),
(4, 'David', 4600.00, 2023),
(5,'Eva',5200.00,2023),
(5,'Eva',5400.00,2024);

SELECT 
	EMPLOYEE_ID,EMPLOYEE_NAME,SALARY,YEAR,
    LAG(SALARY) OVER(PARTITION BY EMPLOYEE_ID ORDER BY YEAR) AS PREV_SALARY,
    SALARY - LAG(SALARY) OVER(PARTITION BY EMPLOYEE_ID ORDER BY YEAR) AS INCR_SALARY
FROM EMPLOYEE_VALUE_WINDOW;

-- (ii). LEAD()

CREATE TABLE PRODUCT_SALES (
    PRODUCTID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(50),
    SALEAMOUNT DECIMAL(10,2),
    SALEDATE DATE
);

INSERT INTO PRODUCT_SALES (PRODUCTID, PRODUCTNAME, SALEAMOUNT, SALEDATE) VALUES
(1, 'PRODUCT A', 500.00, '2025-01-01'),
(2, 'PRODUCT A', 400.00, '2025-02-02'),
(3, 'PRODUCT A', 700.00, '2025-03-01'),
(4, 'PRODUCT A', 500.00, '2025-04-02');

SELECT * FROM PRODUCT_SALES;

SELECT
	PRODUCTID,PRODUCTNAME,SALEDATE,SALEAMOUNT,
    LEAD(SALEAMOUNT) OVER(ORDER BY SALEDATE) AS NEXTMONTHSALE
FROM PRODUCT_SALES;

-- (iii). FIRST_VALUE()

CREATE TABLE EMPLOYEE_SALARY (
    ID SERIAL PRIMARY KEY,
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    YEAR INT
);

INSERT INTO EMPLOYEE_SALARY (EMPLOYEEID, EMPLOYEENAME, SALARY, YEAR) VALUES
(1, 'ALICE', 5000.00, 2021),
(1, 'ALICE', 5500.00, 2022),
(1, 'ALICE', 6000.00, 2023),
(1, 'ALICE', 6500.00, 2024),
(1, 'ALICE', 7000.00, 2025),
(2, 'BOB', 4500.00, 2023),
(2, 'BOB', 4800.00, 2024),
(3, 'CHARLIE', 4000.00, 2023),
(3, 'CHARLIE', 4200.00, 2024),
(4, 'DAVID', 4600.00, 2023),
(4, 'DAVID', 4700.00, 2024),
(5, 'EVA', 5200.00, 2023),
(5, 'EVA', 5400.00, 2024);

SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY,
    FIRST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID) AS FIRST_SALARY
FROM EMPLOYEE_SALARY;

-- (iv). LAST_VALUE()

SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LATEST_SALARY
FROM EMPLOYEE_SALARY;


SELECT
	EMPLOYEEID,EMPLOYEENAME,YEAR,SALARY AS YEAR_WISE_SALARY,
    FIRST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR) AS FIRST_SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LATEST_SALARY,
    LAST_VALUE(SALARY) OVER(PARTITION BY EMPLOYEEID ORDER BY YEAR 
    ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) - SALARY AS SALARY_DIFF_BY_CURRENT_TO_YEAR_WISE
FROM EMPLOYEE_SALARY;

-- (v). NTH_VALUE()

CREATE TABLE EMPLOYEE_SALARY_NTH_WINDOW (
    EMPLOYEEID INT,
    EMPLOYEENAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2),
    SALARYDATE DATE
);

INSERT INTO EMPLOYEE_SALARY_NTH_WINDOW (EMPLOYEEID, EMPLOYEENAME, DEPARTMENT, SALARY, SALARYDATE) VALUES
(1, 'ALICE', 'HR', 5000.00, '2025-01-01'),
(7, 'GRACE', 'HR', 5500.00, '2025-01-07'),
(4, 'DAVID', 'HR', 6000.00, '2025-01-04'),
(6, 'FRANK', 'ENGINEERING', 6500.00, '2025-01-06'),
(2, 'BOB', 'ENGINEERING', 7000.00, '2025-01-02'),
(5, 'EVA', 'ENGINEERING', 7500.00, '2025-01-05'),
(3, 'CHARLIE', 'ENGINEERING', 8000.00, '2025-01-03'),
(8, 'HANK', 'ENGINEERING', 8500.00, '2025-01-08');

SELECT
	*,
    NTH_VALUE(SALARY,2) OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SECOND_LARGEST_SALARY_OF_THE_CURRENT_DEPARTMENT
FROM EMPLOYEE_SALARY_NTH_WINDOW;

-- COALESCE

SELECT * FROM EMPLOYEES;

-- WITHOUT COALESCE
SELECT EMPLOYEE_NAME, SALARY + BONUS AS TOTAL_SALARY FROM EMPLOYEES;

-- WITH COALESCE
SELECT EMPLOYEE_NAME, SALARY, BONUS, SALARY + COALESCE(BONUS,0) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT COALESCE(NULL, NULL, 100, NULL);
